package view;

import service.AdicionarLivro;
import service.AtualizarTabelaEstante;

/**
 *
 * @author Lohanny
 */

public class AdicionaLivrosEstante extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    
    Estante estante;
    
    public AdicionaLivrosEstante(Estante estante) {
        initComponents();
        this.setExtendedState(AdicionaLivrosEstante.MAXIMIZED_BOTH);
        
        this.estante = estante;
        this.atualiza = new AtualizarTabelaEstante(this.estante);
        this.adicao = new AdicionarLivro(this, this.atualiza);
        
    }

    AtualizarTabelaEstante atualiza;
    AdicionarLivro adicao;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTelaInicial = new javax.swing.JButton();
        btnEstante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaNomeLivro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entradaAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        entradaEditora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        entradaPaginas = new javax.swing.JTextField();
        btnCadastra = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 208, 199));

        btnTelaInicial.setBackground(new java.awt.Color(255, 208, 199));
        btnTelaInicial.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnTelaInicial.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaInicial.setText("Tela Inicial");
        btnTelaInicial.setBorder(null);
        btnTelaInicial.setBorderPainted(false);
        btnTelaInicial.setContentAreaFilled(false);
        btnTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaInicial.setFocusPainted(false);
        btnTelaInicial.setOpaque(true);
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });

        btnEstante.setBackground(new java.awt.Color(255, 208, 199));
        btnEstante.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnEstante.setForeground(new java.awt.Color(0, 0, 0));
        btnEstante.setText("Estante");
        btnEstante.setBorder(null);
        btnEstante.setBorderPainted(false);
        btnEstante.setContentAreaFilled(false);
        btnEstante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstante.setFocusPainted(false);
        btnEstante.setOpaque(true);
        btnEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(btnTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(btnEstante)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelaInicial)
                    .addComponent(btnEstante))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Adicionar Livros");

        jLabel2.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do livro");

        entradaNomeLivro.setBackground(new java.awt.Color(255, 189, 177));
        entradaNomeLivro.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaNomeLivro.setForeground(new java.awt.Color(0, 0, 0));
        entradaNomeLivro.setBorder(null);

        jLabel5.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Autor");

        entradaAutor.setBackground(new java.awt.Color(255, 189, 177));
        entradaAutor.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaAutor.setForeground(new java.awt.Color(0, 0, 0));
        entradaAutor.setBorder(null);
        entradaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaAutorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Editora");

        entradaEditora.setBackground(new java.awt.Color(255, 189, 177));
        entradaEditora.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaEditora.setForeground(new java.awt.Color(0, 0, 0));
        entradaEditora.setBorder(null);

        jLabel7.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Páginas");

        entradaPaginas.setBackground(new java.awt.Color(255, 189, 177));
        entradaPaginas.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaPaginas.setForeground(new java.awt.Color(0, 0, 0));
        entradaPaginas.setBorder(null);
        entradaPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPaginasActionPerformed(evt);
            }
        });

        btnCadastra.setBackground(new java.awt.Color(255, 160, 143));
        btnCadastra.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        btnCadastra.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastra.setText("Cadastrar");
        btnCadastra.setBorder(null);
        btnCadastra.setBorderPainted(false);
        btnCadastra.setContentAreaFilled(false);
        btnCadastra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastra.setFocusPainted(false);
        btnCadastra.setOpaque(true);
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnLimpa.setBackground(new java.awt.Color(255, 160, 143));
        btnLimpa.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        btnLimpa.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpa.setText("Limpar");
        btnLimpa.setBorder(null);
        btnLimpa.setBorderPainted(false);
        btnLimpa.setContentAreaFilled(false);
        btnLimpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpa.setFocusPainted(false);
        btnLimpa.setOpaque(true);
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(entradaPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(entradaAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                            .addComponent(entradaNomeLivro)
                            .addComponent(entradaEditora))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstanteActionPerformed
        dispose();
    }//GEN-LAST:event_btnEstanteActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        adicao.AdicionarLivro();
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        entradaNomeLivro.setText("");
        entradaAutor.setText("");
        entradaEditora.setText("");
        entradaPaginas.setText("");
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void entradaPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPaginasActionPerformed

    private void entradaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionaLivrosEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionaLivrosEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionaLivrosEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionaLivrosEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Estante estante = new Estante();
                
                AdicionaLivrosEstante adicao = new AdicionaLivrosEstante(estante);
                adicao.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnEstante;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JTextField entradaAutor;
    private javax.swing.JTextField entradaEditora;
    private javax.swing.JTextField entradaNomeLivro;
    private javax.swing.JTextField entradaPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public String getNomeLivro(){
        return entradaNomeLivro.getText();
    }
    
    public String getAutor(){
        return entradaAutor.getText();
    }
    
    public String getEditora(){
        return entradaEditora.getText();
    }
    
    public String getPaginas(){
        return entradaPaginas.getText();
    }
}
