/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ConexaoBD;
import model.Livros;


/**
 *
 * @author lohcfsz
 */
public class CadastroLivros extends javax.swing.JFrame {
    public static final List<Livros> livros = new ArrayList<>();
    /**
     * Creates new form TelaPrincipal
     */
    public CadastroLivros() {
        initComponents();
        this.setExtendedState(CadastroLivros.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTelaInicial = new javax.swing.JButton();
        btnEstante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaNomeLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entradaData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entradaAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        entradaEditora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        entradaPaginas = new javax.swing.JTextField();
        btnCadastra = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 208, 199));

        btnTelaInicial.setBackground(new java.awt.Color(255, 208, 199));
        btnTelaInicial.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnTelaInicial.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaInicial.setText("Tela Inicial");
        btnTelaInicial.setBorder(null);
        btnTelaInicial.setBorderPainted(false);
        btnTelaInicial.setContentAreaFilled(false);
        btnTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaInicial.setFocusPainted(false);
        btnTelaInicial.setOpaque(true);
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });

        btnEstante.setBackground(new java.awt.Color(255, 208, 199));
        btnEstante.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnEstante.setForeground(new java.awt.Color(0, 0, 0));
        btnEstante.setText("Estante");
        btnEstante.setBorder(null);
        btnEstante.setBorderPainted(false);
        btnEstante.setContentAreaFilled(false);
        btnEstante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstante.setFocusPainted(false);
        btnEstante.setOpaque(true);
        btnEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(btnTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEstante)
                .addGap(442, 442, 442))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelaInicial)
                    .addComponent(btnEstante))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Livros");

        jLabel2.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do livro");

        entradaNomeLivro.setBackground(new java.awt.Color(255, 189, 177));
        entradaNomeLivro.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaNomeLivro.setForeground(new java.awt.Color(0, 0, 0));
        entradaNomeLivro.setBorder(null);

        jLabel3.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ISBN");

        entradaISBN.setBackground(new java.awt.Color(255, 189, 177));
        entradaISBN.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaISBN.setForeground(new java.awt.Color(0, 0, 0));
        entradaISBN.setBorder(null);

        jLabel4.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Publicação");

        entradaData.setBackground(new java.awt.Color(255, 189, 177));
        entradaData.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaData.setForeground(new java.awt.Color(0, 0, 0));
        entradaData.setBorder(null);

        jLabel5.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Autor");

        entradaAutor.setBackground(new java.awt.Color(255, 189, 177));
        entradaAutor.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaAutor.setForeground(new java.awt.Color(0, 0, 0));
        entradaAutor.setBorder(null);

        jLabel6.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Editora");

        entradaEditora.setBackground(new java.awt.Color(255, 189, 177));
        entradaEditora.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaEditora.setForeground(new java.awt.Color(0, 0, 0));
        entradaEditora.setBorder(null);

        jLabel7.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Páginas");

        entradaPaginas.setBackground(new java.awt.Color(255, 189, 177));
        entradaPaginas.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        entradaPaginas.setForeground(new java.awt.Color(0, 0, 0));
        entradaPaginas.setBorder(null);

        btnCadastra.setBackground(new java.awt.Color(255, 160, 143));
        btnCadastra.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        btnCadastra.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastra.setText("Cadastrar");
        btnCadastra.setBorder(null);
        btnCadastra.setBorderPainted(false);
        btnCadastra.setContentAreaFilled(false);
        btnCadastra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastra.setFocusPainted(false);
        btnCadastra.setOpaque(true);
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnLimpa.setBackground(new java.awt.Color(255, 160, 143));
        btnLimpa.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        btnLimpa.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpa.setText("Limpar");
        btnLimpa.setBorder(null);
        btnLimpa.setBorderPainted(false);
        btnLimpa.setContentAreaFilled(false);
        btnLimpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpa.setFocusPainted(false);
        btnLimpa.setOpaque(true);
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(entradaPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(entradaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(entradaNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(entradaData, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(353, 1064, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(entradaData, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        dispose();
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstanteActionPerformed
        Estante telaEstante = new Estante();
        telaEstante.setVisible(true);
    }//GEN-LAST:event_btnEstanteActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        /*TelaInicial inicio = new TelaInicial();
        if(entradaNomeLivro.getText().isEmpty() || entradaISBN.getText().isEmpty() || entradaData.getText().isEmpty() || entradaAutor.getText().isEmpty() || entradaEditora.getText().isEmpty() || entradaPaginas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos os dados devem ser preenchidos.");
        }else{
            Livros livro = new Livros();
            livro.setNomeLivro(entradaNomeLivro.getText());
            livro.setISBN(entradaISBN.getText());
            livro.setDataPublicacao(entradaData.getText());
            livro.setNomeAutor(entradaAutor.getText());
            livro.setEditora(entradaEditora.getText());
            livro.setQntdPaginas(Integer.parseInt(entradaPaginas.getText()));
            ListaLivros.Adicionar(livro);
            if(ListaLivros.listar().isEmpty()){
                JOptionPane.showMessageDialog(null, "Lista vazia.");
            }else{
                JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso.");
            }
        }*/
        
        if(entradaNomeLivro.getText().isEmpty() || entradaISBN.getText().isEmpty() || entradaData.getText().isEmpty() || entradaAutor.getText().isEmpty() || entradaEditora.getText().isEmpty() || entradaPaginas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
        }else{
            Livros livros = new Livros();
            ConexaoBD conexao = new ConexaoBD();
            TelaInicial inicio = new TelaInicial();
            Connection conn = conexao.conectar();
            int resposta;
            livros.setNomeLivro(entradaNomeLivro.getText());
            livros.setISBN(entradaISBN.getText());
            livros.setDataPublicacao(entradaData.getText());
            livros.setNomeAutor(entradaAutor.getText());
            livros.setEditora(entradaEditora.getText());
            livros.setQntdPaginas(Integer.parseInt(entradaPaginas.getText()));
            resposta = conexao.adicionarLivros(livros);
            inicio.atualizarTabela();
            if(resposta == 1){
                JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso.");
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao inserir os dados.");
            }
            conexao.desconectar();
        }
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        TelaInicial inicio = new TelaInicial();
        entradaNomeLivro.setText("");
        entradaISBN.setText("");
        entradaData.setText("");
        entradaAutor.setText("");
        entradaEditora.setText("");
        entradaPaginas.setText("");
        inicio.atualizarTabela();
    }//GEN-LAST:event_btnLimpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnEstante;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JTextField entradaAutor;
    private javax.swing.JTextField entradaData;
    private javax.swing.JTextField entradaEditora;
    private javax.swing.JTextField entradaISBN;
    private javax.swing.JTextField entradaNomeLivro;
    private javax.swing.JTextField entradaPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
