/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConexaoBD;
import model.ListaEstante;
import model.Livros;
import model.LivrosEstante;


/**
 *
 * @author lohcfsz
 */
public class Estante extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Estante() {
        initComponents();
        this.setExtendedState(Estante.MAXIMIZED_BOTH);
    }
    
    public void atualizarTabela(){
        try{
                ConexaoBD conexao = new ConexaoBD();
                Connection conn = conexao.conectar();
                String sql = "SELECT * FROM estantes";
                PreparedStatement stmt = conn.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                List<LivrosEstante> listaLivrosEstante = conexao.getLivrosEstante();
                DefaultTableModel modeloTabela = (DefaultTableModel) tabelaEstante.getModel();
                modeloTabela.setNumRows(0);
                for(LivrosEstante le : listaLivrosEstante){
                    Object[] obj = new Object[]{le.getNomeLivro(), le.getNomeAutor(), le.getEditora(), le.getQntdPaginas()};
                    modeloTabela.addRow(obj);
                }
                rs.close();
                conn.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao listar tabela." + e.getMessage());
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTelaInicial = new javax.swing.JButton();
        btnTelaCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstante = new javax.swing.JTable();
        btnAddLivroEstante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 208, 199));

        btnTelaInicial.setBackground(new java.awt.Color(255, 208, 199));
        btnTelaInicial.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnTelaInicial.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaInicial.setText("Tela Inicial");
        btnTelaInicial.setBorder(null);
        btnTelaInicial.setBorderPainted(false);
        btnTelaInicial.setContentAreaFilled(false);
        btnTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaInicial.setFocusPainted(false);
        btnTelaInicial.setOpaque(true);
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });

        btnTelaCadastro.setBackground(new java.awt.Color(255, 208, 199));
        btnTelaCadastro.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        btnTelaCadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnTelaCadastro.setText("Cadastro de Livros");
        btnTelaCadastro.setBorder(null);
        btnTelaCadastro.setBorderPainted(false);
        btnTelaCadastro.setContentAreaFilled(false);
        btnTelaCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaCadastro.setFocusPainted(false);
        btnTelaCadastro.setOpaque(true);
        btnTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(btnTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTelaCadastro)
                .addGap(278, 278, 278))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelaInicial)
                    .addComponent(btnTelaCadastro))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estante");

        tabelaEstante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Livro", "Nome do Autor", "Editora", "Quantidade Páginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaEstante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaEstanteFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEstante);

        btnAddLivroEstante.setBackground(new java.awt.Color(255, 160, 143));
        btnAddLivroEstante.setFont(new java.awt.Font("URW Gothic", 0, 24)); // NOI18N
        btnAddLivroEstante.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLivroEstante.setText("Adicionar Livro");
        btnAddLivroEstante.setBorderPainted(false);
        btnAddLivroEstante.setContentAreaFilled(false);
        btnAddLivroEstante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddLivroEstante.setFocusPainted(false);
        btnAddLivroEstante.setMaximumSize(new java.awt.Dimension(66, 30));
        btnAddLivroEstante.setMinimumSize(new java.awt.Dimension(66, 30));
        btnAddLivroEstante.setOpaque(true);
        btnAddLivroEstante.setPreferredSize(new java.awt.Dimension(66, 30));
        btnAddLivroEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLivroEstanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddLivroEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1871, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAddLivroEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroActionPerformed
        CadastroLivros telaCadastroLivros = new CadastroLivros();
        telaCadastroLivros.setVisible(true);
    }//GEN-LAST:event_btnTelaCadastroActionPerformed

    private void btnAddLivroEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLivroEstanteActionPerformed
        AdicionaLivrosEstante telaAdicionaLivrosEstante = new AdicionaLivrosEstante();
        telaAdicionaLivrosEstante.setVisible(true);
    }//GEN-LAST:event_btnAddLivroEstanteActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        atualizarTabela();
    }//GEN-LAST:event_formFocusGained

    private void tabelaEstanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaEstanteFocusGained
        atualizarTabela();
    }//GEN-LAST:event_tabelaEstanteFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        atualizarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLivroEstante;
    private javax.swing.JButton btnTelaCadastro;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEstante;
    // End of variables declaration//GEN-END:variables
}
